event:
  name: "Clínica Jesús del Norte"
  url: "http://www.jesusdelnorte.com.pe/"
  date: "December 10, 2016"
  duration: "8 hours"
site:
  lang: "en"
  title: "Certificado de asistencia"
  logo: "static/images/logo.png"
  index:
    message: "Ingrese su DNI para generar el certificado"
    emailPlaceholder: "DNI"
    inputLabel: "DNI"
    submit: "Generar"
certificate:
  logo: ""
  background: "static/images/background.png"
  textLine1: ""
  textLine2: ""
routes:
  certificate: Certificado
errors:
  error: "<strong>Error:</strong> %message%"
  missingEmail: "Missing email address!"
  invalidEmail: "Invalid email address!"
  emailNoExists: "¡El DNI no está en la lista de asistentes!"
  notAttended: "¡No cumpliste con la asistencia!"
  csvError: "Ocurrió un error al leer el fichero .csv"
  csrfError: "¿Haciendo trampa?"
  error404: "404: Página no encontrada"
  error500: "500: Error interno en el servidor"
csv: csv/sample.csv
